"""
app/planning/workflow.py

The shared, Tk-free scheduling workflow (Milestone 4): the one orchestration
of allocation, selected-day generation, saving and freshness that the
desktop PlanningController, the hosted web API (PostgreSQL, backend/) and
the local web API (SQLite) all run. It works on any PlanningService --
the storage lives behind the service's repository (the SQLite
PlanningRepository, or the server's SQLAlchemy repository) -- so there is
one allocator (app/planning/allocation.py), one day engine
(app/optimizer.py via app/planning/service.py), one preference resolution
(PlanningService.resolve_preferences), one set of occurrence rules
(app/planning/occurrence.py) and one provenance recipe
(app/planning/provenance.py) for every client. Nothing here holds state
between calls: an allocation preview is recomputed from persisted inputs
and identified by their fingerprint, never kept in a process.

Reading inputs (read_inputs): one consistent snapshot of a range's tasks
(per RangeScope, deadlines judged in the planning timezone), fixed blocks,
effective preferences and external dependencies, plus their fingerprint.
preview_allocation allocates such a snapshot without saving anything;
preference_views shows each date's effective and inherited preferences with
the stored layers they come from.

Generation (generate) for a contiguous run of dates inside an allocation
range, in one of two modes:

Every generation keeps (plan_reservations; docs/execution-rescheduling.md,
"Manual placements" and "Scope"), whatever the mode:

    - history: a placement whose execution started or finished stays exactly
      as recorded. If it no longer fits the current inputs (an estimate
      changed, a fixed block was added over it) that is a non-blocking
      notice (GenerationOutcome.notices), never a reason to move it;
    - manual intent: the destination of an explicit reschedule (preserved,
      or proven by its recorded reschedule lineage) stays until the user
      releases it (PlanningService.release_manual_placement). If it no
      longer fits, RegenerationRequiredError names it, why, and the
      remedies -- nothing is written;
    - work outside the generated dates: an occurrence the range plans that
      is already live on another date stays there and is not placed again
      (GenerationOutcome.kept_elsewhere). Generation never removes or
      supersedes anything outside the dates it generates.

Kept work is reserved as busy time (only in memory; nothing fake is stored)
and its occurrences are not placed again. Then, in one of two modes:

    FULL (the default): every other saved placement of a generated date is
        replaceable: the date is generated by the day engine around the kept
        work, with the replaceable placements as previous_result -- an
        identical placement keeps its id -- and the result replaces them. A
        replaced placement's never-started execution is cancelled as
        superseded (a system cancellation, never a user skip).

    INCREMENTAL (explicit opt-in): every saved placement of a generated date
        is kept exactly (id, interval, version, execution links) as long as
        it still fits the current inputs, and only newly eligible work is
        scheduled into the time around it. If a kept placement no longer fits
        (its task was deleted, moved, re-timed, or its date's window, fixed
        blocks, engine mode, deadline or dependencies changed),
        RegenerationRequiredError says which and why, and nothing is saved:
        replacing kept work always takes an explicit FULL regeneration.

Every generation first checks freshness: when every requested date's saved
schedule is current for the current inputs, it returns already_current and
writes nothing (no id, version, timestamp, provenance or change-capture
change). Otherwise the engine runs outside any write transaction; then, in
one transaction, the inputs are read again and their fingerprint compared
with the one generation used (StaleInputsError if anything changed --
tasks, blocks, preferences, external dependencies), the saved placements'
versions are compared (VersionConflictError), the reservation state --
saved placements and their versions, manual intent, execution states, and
the occurrences kept outside the generated dates -- is recomputed
(StaleInputsError if it differs), and only then are placements and
provenance written together. A failure anywhere leaves the previous
schedule exactly as it was. A MandatoryTaskSchedulingError from the engine
is raised unchanged, with its per-task reasons.

Explicit rescheduling (reschedule_placement): moves one saved placement to
a new interval after validating the destination with the same hard rules a
kept placement must meet (reschedule_problems). It is not a generation: no
engine run and no provenance record; the dates it touches become stale.

preserve_on_empty (opt-in; the desktop Day page uses it): when a run would
place nothing at all on any generated date -- no work was allocated there,
or none of it fits -- while those dates still have saved placements, it
returns "nothing_placed" (with the run's genuine unscheduled reasons) and
writes nothing, so the previous schedule stays exactly as it was instead of
being replaced by an empty one. Without it (the default) such a run saves
the empty result, as before.

Freshness (day_freshness): per date, CURRENT / STALE (with a StaleReason) /
NONE, recomputed from the persisted record, the recorded range's inputs and
the saved placements. The record keeps only the *count* of unscheduled
tasks, so after a restart their explanations are unknown -- they are never
fabricated from the count.
"""

from __future__ import annotations

import hashlib
import json
import time
import uuid
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field, replace
from datetime import date as date_
from datetime import datetime, timedelta, timezone
from enum import Enum
from zoneinfo import ZoneInfo

from app.mode_objectives import mode_weight
from app.optimizer import DayEvaluation, MandatoryTaskSchedulingError, evaluate_day_output
from app.planning.allocation import AllocationResult, allocate_tasks
from app.planning.application import (
    PROJECT_TEMPLATE,
    GenerationProvenance,
    PlacementReschedule,
    PlanningRange,
    PlanningService,
    RangeScope,
    RescheduleResult,
)
from app.planning.errors import (
    GenerationLimitError,
    InvalidEntityError,
    PlanningError,
    RegenerationRequiredError,
    RescheduleRejectedError,
    ScopeError,
    StaleInputsError,
)
from app.planning.external_dependencies import (
    ExternalDependency,
    allocation_dates,
    explain_unallocated,
    satisfaction_instants,
)
from app.planning.models import (
    PLACEMENT_SNAPSHOT_FIELDS,
    DayScheduleOutput,
    FixedBlock,
    OccurrenceState,
    PlacementOrigin,
    ScheduledTask,
    Task,
    TaskRegistry,
    compute_total_score,
)
from app.planning.occurrence import HISTORY_PROTECTED_STATUSES, occurrence_key, task_occurrence_key
from app.planning.catch_up import CatchUpEvidence, catch_up_evidence
from app.planning.catch_up import task_bonuses as catch_up_task_bonuses
from app.planning.preferences import (
    DayPreferences,
    OptimizerMode,
    PreferenceOverrides,
    PreferenceRecord,
    day_preferences_to_reward_settings,
    resolve_day_preferences,
)
from app.planning.provenance import GenerationRecord, StaleReason, classify_generation, inputs_fingerprint, placements_digest
from app.planning.series import ExpansionResult, expand_occurrences
from app.planning.service import generate_selected_day
from app.planning.time import AmbiguousLocalTimeError, UnsupportedSchedulingWindowError

#: The largest date range one request may read, allocate or generate (a bounded, paginated-by-range API).
MAX_RANGE_DAYS = 62
#: The most tasks one generation plans (allocation and day engine work grow with it).
MAX_GENERATION_TASKS = 2000

#: Kept placements become engine-only reserved intervals under ids derived from theirs (never stored).
_RESERVED_NAMESPACE = uuid.UUID("5d2c7a3e-7a51-4e0e-9a55-2f0c3b1d4e6f")


class GenerationMode(str, Enum):
    FULL = "full"
    INCREMENTAL = "incremental"


class Freshness(str, Enum):
    #: Nothing has been generated or saved for the date.
    NONE = "none"
    #: The saved schedule matches the current inputs and was not changed since it was saved.
    CURRENT = "current"
    #: A saved schedule exists but is out of date (see stale_reason).
    STALE = "stale"


@dataclass(frozen=True)
class SchedulingInputs:
    """One consistent snapshot of everything a range generation reads, plus its fingerprint."""

    start_date: date_
    end_date: date_
    scope: RangeScope
    timezone_name: str
    planning_range: PlanningRange
    preferences_by_date: dict[date_, DayPreferences]
    external: dict[uuid.UUID, ExternalDependency]
    fingerprint: str
    #: The Catch-Up history evidence (app/planning/catch_up.py) when any date uses Catch-Up; its digest is part of
    #: the fingerprint, so changed outcomes make a saved Catch-Up schedule stale and refuse a stale save.
    catch_up: CatchUpEvidence | None = None


@dataclass(frozen=True)
class DayFreshness:
    date: date_
    status: Freshness
    stale_reason: StaleReason | None
    record: GenerationRecord | None
    placements: list[ScheduledTask]


@dataclass(frozen=True)
class AllocationPreview:
    """An allocation computed from persisted inputs (nothing saved), with the fingerprint that identifies them."""

    inputs: SchedulingInputs
    allocation: AllocationResult
    freshness: dict[date_, DayFreshness]
    #: The recurrence expansion of the range that ran first (it may materialize occurrences).
    expansion: ExpansionResult | None = None

    @property
    def fingerprint(self) -> str:
        return self.inputs.fingerprint


@dataclass(frozen=True)
class DayPreferenceView:
    date: date_
    #: What scheduling uses on this date: defaults -> template -> user layer -> date layer.
    effective: DayPreferences
    #: What the date would use without its own layer (defaults -> template -> user layer).
    inherited: DayPreferences
    #: The date's own stored layer, if it has one.
    date_layer: PreferenceRecord | None


@dataclass(frozen=True)
class PreferenceViews:
    """Every layer of a range's preferences, as one consistent read."""

    timezone_name: str
    template: PreferenceOverrides | None
    user_layer: PreferenceRecord | None
    days: dict[date_, DayPreferenceView]


@dataclass(frozen=True)
class PlacementProblem:
    """
    Why a placement that would be kept (or a move's destination) no longer
    fits the current inputs. `kept_as` says why it is kept ("history",
    "manual", "kept"; "destination" for a move); `blocking` whether
    generation refuses to write until it is resolved (history never blocks:
    it stays exactly as recorded); `remedies` what resolves it --
    "edit_constraint", "move" (the explicit reschedule, if legal),
    "release_manual_intent", "choose_another_range", "regenerate_full".
    """

    placement_id: uuid.UUID
    task_id: uuid.UUID
    date: date_
    reason: str
    explanation: str
    kept_as: str = "kept"
    blocking: bool = True
    remedies: tuple[str, ...] = ()


@dataclass(frozen=True)
class GenerationOutcome:
    #: "generated", "already_current" or (preserve_on_empty) "nothing_placed"; the latter two wrote nothing.
    status: str
    mode: GenerationMode
    inputs: SchedulingInputs
    allocation: AllocationResult
    #: Per generated date: the saved result (for already_current: the stored placements, no unscheduled reasons).
    outputs: dict[date_, DayScheduleOutput]
    #: Per generated date: the placements kept exactly as they were (incremental, or protected history).
    kept_ids: dict[date_, list[uuid.UUID]] = field(default_factory=dict)
    reschedule: RescheduleResult | None = None
    #: The recurrence expansion of the allocation range that ran first (docs/recurrence.md).
    expansion: ExpansionResult | None = None
    #: Per generated date: non-blocking problems of kept history (it stays exactly as recorded).
    notices: dict[date_, list[PlacementProblem]] = field(default_factory=dict)
    #: Range task id -> its occurrence's placement outside the generated dates, left there (not placed again).
    kept_elsewhere: dict[uuid.UUID, ScheduledTask] = field(default_factory=dict)
    #: Per generated date: its objective under its mode, recomputed (app/optimizer.evaluate_day_output).
    evaluations: dict[date_, DayEvaluation] = field(default_factory=dict)


def range_dates(start_date: date_, end_date: date_) -> list[date_]:
    return [start_date + timedelta(days=offset) for offset in range((end_date - start_date).days + 1)]


def check_range(start_date: date_, end_date: date_) -> None:
    if end_date < start_date:
        raise ScopeError(f"end_date {end_date} is before start_date {start_date}.")
    if (end_date - start_date).days + 1 > MAX_RANGE_DAYS:
        raise ScopeError(f"a range may span at most {MAX_RANGE_DAYS} days.")


def expand_range(service: PlanningService, start_date: date_, end_date: date_, *, clock=None) -> ExpansionResult:
    """
    Materialize the recurring occurrences of an allocation range before its
    inputs are read (app/planning/series.py): bounded by the range limit and
    the expansion budget, idempotent, in its own transaction. Every persisted
    generation path (generate, preview_allocation, the desktop's range and
    allocation runs) calls it first, so allocation always sees the concrete
    occurrences and never a series definition.
    """
    check_range(start_date, end_date)
    return expand_occurrences(service, start_date, end_date, clock=clock)


# -----------------------------------------------------------------------------
# Inputs, allocation, freshness
# -----------------------------------------------------------------------------


def read_inputs(
    service: PlanningService,
    start_date: date_,
    end_date: date_,
    *,
    scope: RangeScope,
    timezone_name: str,
    template: object = PROJECT_TEMPLATE,
    clock=None,
) -> SchedulingInputs:
    """
    Everything a generation of [start_date, end_date] reads, as one consistent
    snapshot -- including, when a date uses Catch-Up, one bulk read of the
    history evidence (as of the current UTC day; app/planning/catch_up.py).
    """
    dates = range_dates(start_date, end_date)
    evidence = None
    with service.transaction():
        planning_range = service.load_range(start_date, end_date, scope=scope, timezone_name=timezone_name)
        preferences_by_date = service.resolve_preferences(dates, timezone_name, template=template)
        external = service.external_dependencies(planning_range.tasks.tasks.values(), start_date, end_date, timezone_name)
        if any(day.optimizer_mode == OptimizerMode.CATCH_UP for day in preferences_by_date.values()):
            evidence = catch_up_evidence(service, (clock or _utcnow)())
    fingerprint = inputs_fingerprint(
        start_date=start_date, end_date=end_date, scope=scope.value, timezone_name=timezone_name,
        tasks=[*planning_range.tasks.tasks.values(), *planning_range.series.tasks.values()],
        fixed_blocks=[block for day in dates for block in planning_range.fixed_blocks_by_date[day]],
        preferences_by_date=preferences_by_date, external_dependencies=external,
    )
    if evidence is not None:
        fingerprint = hashlib.sha256(f"{fingerprint}|catch_up:{evidence.digest}".encode("utf-8")).hexdigest()
    return SchedulingInputs(
        start_date=start_date, end_date=end_date, scope=scope, timezone_name=timezone_name,
        planning_range=planning_range, preferences_by_date=preferences_by_date, external=external,
        fingerprint=fingerprint, catch_up=evidence,
    )


def allocate(inputs: SchedulingInputs) -> AllocationResult:
    """Allocation of the inputs' range (never generates placements), with external-dependency explanations."""
    planning_range = inputs.planning_range
    result = allocate_tasks(
        start_date=inputs.start_date, end_date=inputs.end_date, tasks=planning_range.tasks,
        task_ids=planning_range.task_ids, preferences_by_date=inputs.preferences_by_date,
        fixed_blocks_by_date=planning_range.fixed_blocks_by_date,
        external_dependency_dates=allocation_dates(inputs.external),
    )
    return explain_unallocated(result, planning_range.tasks.tasks, inputs.external)


def preview_allocation(
    service: PlanningService,
    start_date: date_,
    end_date: date_,
    *,
    scope: RangeScope,
    timezone_name: str,
    template: object = PROJECT_TEMPLATE,
) -> AllocationPreview:
    """
    Allocate a range from persisted inputs (never generates or saves
    placements); see generate's expected_fingerprint. The range's recurring
    occurrences are materialized first (expand_range), exactly as generate
    does, so a preview and the generation it confirms read the same inputs.
    """
    check_range(start_date, end_date)
    expansion = expand_range(service, start_date, end_date)
    inputs = read_inputs(service, start_date, end_date, scope=scope, timezone_name=timezone_name, template=template)
    allocation = allocate(inputs)
    freshness = day_freshness(service, range_dates(start_date, end_date), timezone_name, template=template)
    return AllocationPreview(inputs=inputs, allocation=allocation, freshness=freshness, expansion=expansion)


def preference_views(
    service: PlanningService,
    start_date: date_,
    end_date: date_,
    timezone_name: str,
    *,
    template: object = PROJECT_TEMPLATE,
) -> PreferenceViews:
    """Effective and inherited preferences of each date, with the stored layers they come from."""
    check_range(start_date, end_date)
    dates = range_dates(start_date, end_date)
    layer = service.preference_template() if template is PROJECT_TEMPLATE else template
    with service.transaction():
        user = service.user_preferences()
        by_date = service.date_preferences_for_range(start_date, end_date)
        effective = service.resolve_preferences(dates, timezone_name, template=layer)
    days = {
        day: DayPreferenceView(
            date=day, effective=effective[day],
            inherited=resolve_day_preferences(date=day, timezone=timezone_name, yaml_overrides=layer,
                                              user_overrides=user.overrides if user is not None else None),
            date_layer=by_date.get(day),
        )
        for day in dates
    }
    return PreferenceViews(timezone_name=timezone_name, template=layer, user_layer=user, days=days)


def day_freshness(
    service: PlanningService, dates: Iterable[date_], timezone_name: str, *, template: object = PROJECT_TEMPLATE
) -> dict[date_, DayFreshness]:
    """Each date's persisted freshness (see the module docstring); each recorded range's inputs are read once."""
    dates = sorted(set(dates))
    if not dates:
        return {}
    records = service.generation_records(dates[0], dates[-1])
    placements_by_date = service.placements_for_range(dates[0], dates[-1])
    fingerprints: dict[tuple, str | None] = {}
    result: dict[date_, DayFreshness] = {}
    for day in dates:
        record = records.get(day)
        placements = placements_by_date[day]
        current = None
        if record is not None:
            key = (record.range_start, record.range_end, record.range_scope)
            if key not in fingerprints:
                try:
                    fingerprints[key] = read_inputs(
                        service, record.range_start, record.range_end, scope=RangeScope(record.range_scope),
                        timezone_name=timezone_name, template=template,
                    ).fingerprint
                except (PlanningError, ValueError):
                    fingerprints[key] = None  # the recorded inputs can no longer be recomputed
            current = fingerprints[key]
        is_current, reason = classify_generation(
            record, has_placements=bool(placements), current_fingerprint=current,
            current_placements_digest=placements_digest(placements),
        )
        status = Freshness.NONE if is_current is None else Freshness.CURRENT if is_current else Freshness.STALE
        result[day] = DayFreshness(date=day, status=status, stale_reason=reason, record=record, placements=placements)
    return result


# -----------------------------------------------------------------------------
# Generation
# -----------------------------------------------------------------------------


def generate(
    service: PlanningService,
    *,
    range_start: date_,
    range_end: date_,
    generate_start: date_ | None = None,
    generate_end: date_ | None = None,
    scope: RangeScope = RangeScope.PLANNED,
    timezone_name: str,
    mode: GenerationMode = GenerationMode.FULL,
    expected_fingerprint: str | None = None,
    template: object = PROJECT_TEMPLATE,
    clock=None,
    preserve_on_empty: bool = False,
    deadline: float | None = None,
) -> GenerationOutcome:
    """
    `deadline` (time.monotonic() value, optional): the run stops with
    GenerationLimitError -- saving nothing -- when it is passed between dates
    or before the save.

    Allocate [range_start, range_end] from persisted inputs and generate
    [generate_start, generate_end] (default: the whole range) -- see the
    module docstring. expected_fingerprint, when given, is the fingerprint
    of the allocation preview the caller acted on (StaleInputsError if the
    inputs changed since). History and manual placements are always
    protected; there is no switch to turn that off.
    """
    check_range(range_start, range_end)
    generate_start = generate_start or range_start
    generate_end = generate_end or range_end
    if not range_start <= generate_start <= generate_end <= range_end:
        raise ScopeError("the generated dates must lie inside the allocation range.")

    expansion = expand_range(service, range_start, range_end, clock=clock)
    inputs = read_inputs(
        service, range_start, range_end, scope=scope, timezone_name=timezone_name, template=template, clock=clock
    )
    if expected_fingerprint is not None and expected_fingerprint != inputs.fingerprint:
        raise StaleInputsError(expected_fingerprint, inputs.fingerprint)
    if len(inputs.planning_range.tasks.tasks) > MAX_GENERATION_TASKS:
        raise GenerationLimitError(f"a generation plans at most {MAX_GENERATION_TASKS} tasks; choose a shorter range.")
    dates = range_dates(generate_start, generate_end)

    freshness = day_freshness(service, dates, timezone_name, template=template)
    if all(state.status == Freshness.CURRENT for state in freshness.values()):
        outputs = {day: _stored_output(service, day, freshness[day], inputs) for day in dates}
        return GenerationOutcome(status="already_current", mode=mode, inputs=inputs, allocation=allocate(inputs),
                                 outputs=outputs, expansion=expansion)

    reservations = plan_reservations(service, inputs, dates, mode=mode)
    allocation = allocate(inputs)
    outcome = generate_from(
        service, allocation, inputs, dates, mode=mode, template=template, clock=clock,
        preserve_on_empty=preserve_on_empty, reservations=reservations, deadline=deadline,
    )
    return replace(outcome, expansion=expansion)


# -----------------------------------------------------------------------------
# Reservations: what a generation keeps and what it must not place again
# -----------------------------------------------------------------------------


#: Why a kept placement is kept (PlacementProblem.kept_as).
KEPT_HISTORY = "history"  # its execution started or finished: immutable history
KEPT_MANUAL = "manual"  # the user's manual intent (a deliberate move), until released
KEPT_EXISTING = "kept"  # an incremental generation keeps every valid saved placement


@dataclass(frozen=True)
class DayReservation:
    """One generated date's saved placements and which of them the generation keeps (and why)."""

    date: date_
    stored: list[ScheduledTask]
    #: Kept placement id -> KEPT_HISTORY / KEPT_MANUAL / KEPT_EXISTING.
    kept: dict[uuid.UUID, str]
    #: The kept placements' tasks (including deleted ones).
    kept_tasks: dict[uuid.UUID, Task]
    blocking: list[PlacementProblem]
    notices: list[PlacementProblem]


@dataclass(frozen=True)
class Reservations:
    """Everything a generation of `dates` keeps, computed from one read (see plan_reservations)."""

    dates: list[date_]
    days: dict[date_, DayReservation]
    #: Occurrence keys of the kept placements on the generated dates: never placed again by this run.
    kept_keys: dict[tuple, ScheduledTask]
    #: Range task id -> its occurrence's live placement outside the generated dates: left there, not placed again.
    elsewhere: dict[uuid.UUID, ScheduledTask]
    #: Digest of every record the plan was made from (placements, versions, manual intent, execution statuses):
    #: recomputed inside the write transaction; a difference refuses the save.
    token: str

    @property
    def blocking(self) -> list[PlacementProblem]:
        return [problem for day in self.dates for problem in self.days[day].blocking]

    def excluded_task_ids(self, tasks: TaskRegistry) -> set[uuid.UUID]:
        """Range tasks whose occurrence is kept on a generated date or live elsewhere."""
        excluded = set(self.elsewhere)
        for day in self.dates:
            for task_id in tasks.tasks:
                task = tasks.get(task_id)
                if task_occurrence_key(task, day) in self.kept_keys or task_occurrence_key(task, None) in self.kept_keys:
                    excluded.add(task_id)
        return excluded


def plan_reservations(
    service: PlanningService, inputs: SchedulingInputs, dates: list[date_], *, mode: GenerationMode
) -> Reservations:
    """
    What a generation of `dates` keeps (docs/execution-rescheduling.md,
    "Manual placements" and "Scope"):

        - every saved placement whose execution started or finished
          (HISTORY_PROTECTED_STATUSES) -- immutable history;
        - every placement carrying manual intent (preserved, or proven by a
          recorded reschedule lineage: PlanningService.preserved_placement_ids);
        - INCREMENTAL also every other saved placement that still fits;
        - and, outside the generated dates, every live placement of an
          occurrence the range plans: it stays where it is, and this run does
          not place that occurrence again (moving it is the explicit
          reschedule).

    Kept work is checked against the current inputs: a manual or incremental
    placement that no longer fits is a *blocking* problem (the generation
    writes nothing; remedies say what resolves it); history that no longer
    fits is a non-blocking notice -- it stays exactly as recorded.
    """
    tasks = inputs.planning_range.tasks
    days: dict[date_, DayReservation] = {}
    kept_keys: dict[tuple, ScheduledTask] = {}
    token_rows: list[list] = []
    for day in dates:
        stored = service.placements_for_date(day)
        statuses = service.placement_execution_statuses(placement.id for placement in stored)
        preserved = service.preserved_placement_ids(stored)
        kept: dict[uuid.UUID, str] = {}
        for placement in stored:
            if statuses.get(placement.id) in HISTORY_PROTECTED_STATUSES:
                kept[placement.id] = KEPT_HISTORY
            elif placement.id in preserved:
                kept[placement.id] = KEPT_MANUAL
            elif mode == GenerationMode.INCREMENTAL:
                kept[placement.id] = KEPT_EXISTING
        kept_placements = [placement for placement in stored if placement.id in kept]
        kept_tasks = service.get_tasks_including_deleted(placement.task_id for placement in kept_placements)
        problems = _kept_problems(
            service, kept_placements, kept_tasks, inputs, day,
            full_check_ids={pid for pid, kind in kept.items() if kind != KEPT_HISTORY},
            kinds=kept, upcoming=set(tasks.tasks),
        )
        blocking = [problem for problem in problems if problem.blocking]
        notices = [problem for problem in problems if not problem.blocking]
        days[day] = DayReservation(day, stored, kept, dict(kept_tasks), blocking, notices)
        for placement in kept_placements:
            task = kept_tasks.get(placement.task_id)
            if task is not None:
                kept_keys.setdefault(occurrence_key(placement, task), placement)
        token_rows.extend(
            [str(p.id), p.version, p.planned_date.isoformat(), statuses.get(p.id), p.id in preserved] for p in stored
        )

    elsewhere = _placements_elsewhere(service, set(tasks.tasks), tasks, set(dates))
    token_rows.extend([str(task_id), str(p.id), p.version, p.planned_date.isoformat()]
                      for task_id, p in sorted(elsewhere.items(), key=lambda item: str(item[0])))
    elsewhere_statuses = service.placement_execution_statuses(p.id for p in elsewhere.values())
    token_rows.extend([str(pid), status] for pid, status in sorted(elsewhere_statuses.items(), key=lambda i: str(i[0])))
    token = hashlib.sha256(json.dumps(token_rows, sort_keys=True, default=str).encode("utf-8")).hexdigest()
    return Reservations(dates=list(dates), days=days, kept_keys=kept_keys, elsewhere=elsewhere, token=token)


def generate_from(
    service: PlanningService,
    allocation: AllocationResult,
    inputs: SchedulingInputs,
    dates: list[date_],
    *,
    mode: GenerationMode = GenerationMode.FULL,
    template: object = PROJECT_TEMPLATE,
    clock=None,
    preserve_on_empty: bool = False,
    reservations: Reservations | None = None,
    deadline: float | None = None,
) -> GenerationOutcome:
    """
    Generate `dates` (contiguous, inside the inputs' range) from a given
    allocation and save them (see generate). Kept work (plan_reservations)
    is reserved and never replaced; a blocking problem with it raises
    RegenerationRequiredError before anything is written.
    """
    if reservations is None:
        reservations = plan_reservations(service, inputs, dates, mode=mode)
    if reservations.blocking:
        raise RegenerationRequiredError(reservations.blocking)
    excluded = reservations.excluded_task_ids(inputs.planning_range.tasks)
    outputs: dict[date_, DayScheduleOutput] = {}
    expected: dict[uuid.UUID, int] = {}
    kept: dict[date_, list[uuid.UUID]] = {}
    for day in dates:
        _check_deadline(deadline)
        try:
            output = _generate_date(service, allocation, inputs, day, reservations=reservations, excluded=excluded,
                                    mode=mode)
        except MandatoryTaskSchedulingError as error:
            error.failed_date = day  # which date could not be generated (the error names only tasks)
            raise
        stored = reservations.days[day].stored
        outputs[day] = _with_category_snapshots(output, stored, service)
        expected.update({placement.id: placement.version for placement in stored})
        kept[day] = sorted(reservations.days[day].kept, key=str)
    order = _kept_order_problems(service, outputs, reservations, inputs)
    if order:
        raise RegenerationRequiredError(order)

    notices = {day: reservations.days[day].notices for day in dates if reservations.days[day].notices}
    if preserve_on_empty and expected and not any(output.placements for output in outputs.values()):
        # Nothing new to show and saved work would be wiped: keep the previous schedule untouched.
        return GenerationOutcome(status="nothing_placed", mode=mode, inputs=inputs, allocation=allocation,
                                 outputs=outputs, kept_ids=kept, notices=notices,
                                 kept_elsewhere=dict(reservations.elsewhere))

    _check_deadline(deadline)  # last chance: once the save starts it runs to its commit
    now = (clock or _utcnow)()
    provenance = GenerationProvenance(
        allocation_id=allocation.id, range_start=inputs.start_date, range_end=inputs.end_date,
        range_scope=inputs.scope.value, fingerprint=inputs.fingerprint, timezone=inputs.timezone_name,
        engine_modes={day: inputs.preferences_by_date[day].optimizer_mode for day in dates}, generated_at=now,
    )
    with service.transaction():
        # The write transaction re-reads every input: a change since generation started -- to any task, series,
        # block, preference or external dependency, to a placement's manual intent, to an execution's state, or to
        # a placement kept outside the generated dates -- refuses the save. Nothing is written in part.
        again = read_inputs(
            service, inputs.start_date, inputs.end_date, scope=inputs.scope, timezone_name=inputs.timezone_name,
            template=template, clock=clock,
        )
        if again.fingerprint != inputs.fingerprint:
            raise StaleInputsError(inputs.fingerprint, again.fingerprint)
        current = plan_reservations(service, inputs, dates, mode=mode)
        if current.token != reservations.token:
            raise StaleInputsError(
                reservations.token, current.token,
                "Saved placements, manual placements or execution states of these dates changed while the schedule "
                "was being generated. Nothing was saved; generate again.",
            )
        result = service.reschedule_range(
            dates[0], dates[-1], outputs, expected_versions=expected, provenance=provenance
        )
    return GenerationOutcome(
        status="generated", mode=mode, inputs=inputs, allocation=allocation, outputs=outputs, kept_ids=kept,
        reschedule=result, notices=notices, kept_elsewhere=dict(reservations.elsewhere),
        evaluations=evaluate_outputs(inputs, outputs, allocation),
    )


def evaluate_outputs(
    inputs: SchedulingInputs, outputs: Mapping[date_, DayScheduleOutput], allocation: AllocationResult | None = None
) -> dict[date_, DayEvaluation]:
    """Each date's objective under its mode (reporting only; nothing stored changes)."""
    evaluations = {}
    for day, output in outputs.items():
        preferences = inputs.preferences_by_date.get(day)
        if preferences is None:
            continue
        bonuses = _catch_up_bonuses(inputs, day, allocation)[0] if allocation is not None else None
        try:
            evaluations[day] = evaluate_day_output(output, preferences, task_bonuses=bonuses)
        except (UnsupportedSchedulingWindowError, AmbiguousLocalTimeError):
            continue
    return evaluations


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


def _check_deadline(deadline: float | None) -> None:
    if deadline is not None and time.monotonic() > deadline:
        raise GenerationLimitError("The schedule took too long to generate and was not saved. "
                                   "Try fewer dates or fewer tasks.")


def _with_category_snapshots(
    output: DayScheduleOutput, stored: list[ScheduledTask], service: PlanningService
) -> DayScheduleOutput:
    """
    The output as it will be saved: a placement the engine kept (same id)
    keeps its stored planning snapshot, origin and manual intent; a new one
    takes its task's snapshot now (category, name, tags, points, estimate,
    type) and is generated -- so what generation returns is exactly what is
    stored.
    """
    by_id = {placement.id: placement for placement in stored}
    new_tasks = {placement.task_id: output.tasks.get(placement.task_id)
                 for placement in output.placements if placement.id not in by_id}
    snapshots = service.placement_snapshots(new_tasks.values()) if new_tasks else {}
    placements = []
    for placement in output.placements:
        previous = by_id.get(placement.id)
        if previous is not None:
            placements.append(placement.model_copy(update={
                **{name: getattr(previous, name) for name in PLACEMENT_SNAPSHOT_FIELDS},
                "origin": previous.origin, "preserved": previous.preserved}))
        else:
            current = snapshots[placement.task_id]
            placements.append(placement.model_copy(update={
                **{name: getattr(placement, name) if getattr(placement, name) is not None else current[name]
                   for name in PLACEMENT_SNAPSHOT_FIELDS},
                "origin": placement.origin or PlacementOrigin.GENERATED}))
    return output.model_copy(update={"placements": placements})


def _stored_output(service: PlanningService, day: date_, state: DayFreshness, inputs: SchedulingInputs) -> DayScheduleOutput:
    """The saved result of a date, without unscheduled explanations (only their count was saved)."""
    tz = state.record.timezone if state.record is not None else inputs.timezone_name
    return service.stored_day_output(day, tz) or DayScheduleOutput(date=day, timezone=tz)


def _generate_date(
    service: PlanningService,
    allocation: AllocationResult,
    inputs: SchedulingInputs,
    day: date_,
    *,
    reservations: Reservations,
    excluded: set[uuid.UUID],
    mode: GenerationMode,
) -> DayScheduleOutput:
    """
    The date's new output: its kept placements exactly as they are, plus the
    day engine's placements of the date's other allocated work around them.
    FULL hands the engine the date's replaceable (generated, unprotected)
    placements as previous_result, so an identical placement keeps its id.
    """
    preferences = inputs.preferences_by_date[day]
    reservation = reservations.days[day]
    stored = reservation.stored
    tasks = inputs.planning_range.tasks
    blocks = inputs.planning_range.fixed_blocks_by_date[day]
    kept = [placement for placement in stored if placement.id in reservation.kept]
    kept_tasks = service.get_tasks_including_deleted(placement.task_id for placement in kept)

    satisfaction = dict(satisfaction_instants(inputs.external))
    for placement in [*kept, *reservations.kept_keys.values()]:
        satisfaction[placement.task_id] = (placement.planned_date, placement.planned_end)
    for task_id, placement in reservations.elsewhere.items():
        satisfaction[task_id] = (placement.planned_date, placement.planned_end)
    for task_id in excluded:
        task = tasks.get(task_id)
        if task is None:
            continue
        for key in (task_occurrence_key(task, day), task_occurrence_key(task, None)):
            if key in reservations.kept_keys:
                held = reservations.kept_keys[key]
                satisfaction[task_id] = (held.planned_date, held.planned_end)

    busy = _busy_blocks(kept, blocks, preferences, day)
    sub_allocation = allocation.model_copy(update={
        "assignments": {task_id: assigned for task_id, assigned in allocation.assignments.items() if task_id not in excluded}
    })
    previous = None
    if mode == GenerationMode.FULL:
        replaceable = [placement for placement in stored if placement.id not in reservation.kept]
        previous = DayScheduleOutput(
            date=day, timezone=preferences.timezone,
            tasks=service.get_tasks(placement.task_id for placement in replaceable),
            placements=replaceable, total_score=compute_total_score(replaceable),
        ) if replaceable else None
    bonuses, explanations = _catch_up_bonuses(inputs, day, sub_allocation)
    generated, _ = generate_selected_day(
        sub_allocation, day, tasks, {day: preferences}, {day: [*blocks, *busy]}, previous_result=previous,
        external_dependency_satisfaction=satisfaction, task_bonuses=bonuses,
    )
    if explanations:
        # A bounded explanation on each new Catch-Up placement (never the history itself; well under 4 KiB).
        generated = generated.model_copy(update={"placements": [
            placement.model_copy(update={"optimization_metadata": {
                **placement.optimization_metadata, "catch_up": explanations[placement.task_id]}})
            if placement.task_id in explanations else placement
            for placement in generated.placements
        ]})

    registry = TaskRegistry(tasks={**generated.tasks.tasks, **{p.task_id: kept_tasks[p.task_id] for p in kept}})
    placements = [*kept, *generated.placements]
    return DayScheduleOutput(
        date=day, timezone=generated.timezone, fixed_blocks=list(blocks), tasks=registry, placements=placements,
        unscheduled=generated.unscheduled, total_score=compute_total_score(placements),
    )


def _busy_blocks(
    kept: list[ScheduledTask], blocks: list[FixedBlock], preferences, day: date_
) -> list[FixedBlock]:
    """
    Kept placements as busy time for the day engine: each kept interval,
    clipped to the date's window, minus fixed blocks and time already
    reserved. (Kept history may overlap a fixed block added later or another
    kept placement; it stays as recorded, and only its free part is reserved.)
    """
    try:
        window_start, window_end = preferences.to_local_day_window().to_utc_instants()
    except (UnsupportedSchedulingWindowError, AmbiguousLocalTimeError):
        return []
    taken = sorted((block.planned_start, block.planned_end) for block in blocks)
    busy: list[FixedBlock] = []
    for placement in sorted(kept, key=lambda item: (item.planned_start, str(item.id))):
        segments = [(max(placement.planned_start, window_start), min(placement.planned_end, window_end))]
        for start, end in taken:
            segments = [piece for seg_start, seg_end in segments for piece in (
                (seg_start, min(seg_end, start)), (max(seg_start, end), seg_end))]
            segments = [(seg_start, seg_end) for seg_start, seg_end in segments if seg_start < seg_end]
        for index, (start, end) in enumerate(segments):
            busy.append(FixedBlock(
                id=uuid.uuid5(_RESERVED_NAMESPACE, str(placement.id) if index == 0 else f"{placement.id}/{index}"),
                user_id=placement.user_id, label="(kept work)", category="reserved", planned_date=day,
                timezone=preferences.timezone, planned_start=start, planned_end=end,
            ))
            taken.append((start, end))
        taken.sort()
    return busy


def _kept_order_problems(
    service: PlanningService,
    outputs: Mapping[date_, DayScheduleOutput],
    reservations: Reservations,
    inputs: SchedulingInputs,
) -> list[PlacementProblem]:
    """
    A kept (manual or incremental) placement whose dependency is planned by
    this run must still come after it: the day engine treats kept work as
    busy time and cannot order around it, so the result is checked here and
    a violation blocks the whole generation (nothing is written).
    """
    range_ids = set(inputs.planning_range.tasks.tasks)
    dates = set(reservations.dates)
    problems: list[PlacementProblem] = []
    stored_dependencies: dict[uuid.UUID, list[ScheduledTask]] | None = None
    for day in reservations.dates:
        reservation = reservations.days[day]
        same_day = {placement.task_id: placement for placement in outputs[day].placements}
        for placement in reservation.stored:
            kept_as = reservation.kept.get(placement.id)
            task = reservation.kept_tasks.get(placement.task_id)
            if kept_as in (None, KEPT_HISTORY) or task is None or task.deleted_at is not None:
                continue
            for dependency in task.dependency_ids:
                if dependency not in range_ids:
                    continue  # judged up front (_kept_problems)
                if stored_dependencies is None:
                    wanted = {d for t in inputs.planning_range.tasks.tasks.values() for d in t.dependency_ids}
                    stored_dependencies = service.active_placements_for_tasks(wanted)
                others = [p for other_day, output in outputs.items() if other_day != day
                          for p in output.placements if p.task_id == dependency]
                others += [p for p in stored_dependencies.get(dependency, []) if p.planned_date not in dates]
                if not _dependency_done_by(dependency, placement, day, same_day, {dependency: others}, inputs.external):
                    problems.append(PlacementProblem(
                        placement.id, placement.task_id, day, "dependency_not_satisfied",
                        f"its dependency {dependency} would not finish before it.", kept_as=kept_as,
                        blocking=True, remedies=_remedies("dependency_not_satisfied", kept_as),
                    ))
                    break
    return problems


def _catch_up_bonuses(
    inputs: SchedulingInputs, day: date_, allocation: AllocationResult
) -> tuple[dict[uuid.UUID, float] | None, dict[uuid.UUID, dict]]:
    """The Catch-Up bonuses and explanations of the tasks allocated to `day` (none for other modes)."""
    preferences = inputs.preferences_by_date[day]
    if preferences.optimizer_mode != OptimizerMode.CATCH_UP or inputs.catch_up is None:
        return None, {}
    tasks = inputs.planning_range.tasks
    allocated = [tasks.get(task_id) for task_id, assigned in allocation.assignments.items()
                 if assigned == day and tasks.get(task_id) is not None]
    weight = mode_weight(day_preferences_to_reward_settings(preferences).weight_importance)
    return catch_up_task_bonuses(inputs.catch_up, allocated, weight)


def _placements_elsewhere(
    service: PlanningService, task_ids: set[uuid.UUID], tasks: TaskRegistry, dates: set[date_]
) -> dict[uuid.UUID, ScheduledTask]:
    """
    For each task (in task_ids) whose occurrence already has a live placement
    on a date outside `dates`: the earliest such placement. An occurrence of a
    recurring series counts its own placements on any date and a legacy
    placement of its series on its original slot date
    (app/planning/occurrence.py). A series definition is never planned itself.
    """
    found: dict[uuid.UUID, ScheduledTask] = {}
    groups = {task_id: list(group) for task_id, group in service.active_placements_for_tasks(task_ids).items()}
    occurrences = {task_id: tasks.get(task_id) for task_id in task_ids
                   if tasks.get(task_id) is not None and tasks.get(task_id).is_occurrence}
    legacy = service.active_placements_for_tasks({task.series_id for task in occurrences.values()})
    for task_id, task in occurrences.items():
        groups.setdefault(task_id, []).extend(
            placement for placement in legacy.get(task.series_id, []) if placement.planned_date == task.occurrence_slot
        )
    for task_id, group in groups.items():
        task = tasks.get(task_id)
        if task is None or task.recurrence is not None:
            continue
        for placement in sorted(group, key=lambda p: (p.planned_date, p.planned_start, str(p.id))):
            if placement.planned_date not in dates:
                found.setdefault(task_id, placement)
    return found


def _minutes(start: datetime, end: datetime) -> float:
    return (end - start).total_seconds() / 60


#: What resolves a kept-placement problem (PlacementProblem.remedies).
_CONSTRAINT_REASONS = frozenset({
    "outside_day_window", "overlaps_fixed_block", "required_date_changed", "duration_changed", "deadline_missed",
    "engine_mode_changed", "dependency_not_satisfied", "unsupported_day_window",
})


def _remedies(reason: str, kept_as: str) -> tuple[str, ...]:
    if kept_as == KEPT_HISTORY:
        return ()  # history is never changed; nothing to resolve
    remedies: list[str] = []
    if reason in _CONSTRAINT_REASONS:
        remedies.append("edit_constraint")
    if reason == "task_out_of_range":
        remedies.append("choose_another_range")
    if reason != "task_deleted":
        remedies.append("move")
    if kept_as == KEPT_MANUAL:
        remedies.append("release_manual_intent")
    if kept_as == KEPT_EXISTING:
        remedies.append("regenerate_full")
    return tuple(remedies)


def _kept_problems(
    service: PlanningService,
    kept: list[ScheduledTask],
    kept_tasks: Mapping[uuid.UUID, Task],
    inputs: SchedulingInputs,
    day: date_,
    *,
    full_check_ids: set[uuid.UUID],
    kinds: Mapping[uuid.UUID, str] | None = None,
    upcoming: set[uuid.UUID] = frozenset(),
) -> list[PlacementProblem]:
    """
    Why kept placements no longer fit the current inputs. Every kept placement
    is checked for reservability (inside the date's window, clear of fixed
    blocks and of each other); those in `full_check_ids` must also still be a
    valid placement of their task (required date, duration, deadline, engine
    mode, dependencies). `kinds` says why each is kept: a history placement's
    problems never block (it stays as recorded); others block. A dependency
    among `upcoming` (scheduled by this run) is left to the day engine.
    """
    kinds = kinds or {}
    preferences = inputs.preferences_by_date[day]
    blocks = inputs.planning_range.fixed_blocks_by_date[day]
    problems: list[PlacementProblem] = []

    def problem(placement: ScheduledTask, reason: str, explanation: str) -> None:
        kept_as = kinds.get(placement.id, KEPT_EXISTING)
        problems.append(PlacementProblem(
            placement.id, placement.task_id, day, reason, explanation, kept_as=kept_as,
            blocking=kept_as != KEPT_HISTORY, remedies=_remedies(reason, kept_as),
        ))

    try:
        window_start, window_end = preferences.to_local_day_window().to_utc_instants()
    except (UnsupportedSchedulingWindowError, AmbiguousLocalTimeError) as error:
        for placement in kept:
            problem(placement, "unsupported_day_window", str(error))
        return problems

    in_range = inputs.planning_range.tasks
    dependency_ids = {dep for task in kept_tasks.values() for dep in task.dependency_ids}
    dependency_placements = service.active_placements_for_tasks(dependency_ids) if full_check_ids else {}
    kept_by_task = {placement.task_id: placement for placement in kept}

    for placement in sorted(kept, key=lambda item: (item.planned_start, str(item.id))):
        task = kept_tasks.get(placement.task_id)
        if placement.planned_start < window_start or placement.planned_end > window_end:
            problem(placement, "outside_day_window", "it lies outside this date's day window.")
        clash = next(
            (b for b in blocks if placement.planned_start < b.planned_end and b.planned_start < placement.planned_end), None
        )
        if clash is not None:
            problem(placement, "overlaps_fixed_block", f"it overlaps the fixed block {clash.label!r}.")
        other = next((o for o in kept if o.id != placement.id
                      and placement.planned_start < o.planned_end and o.planned_start < placement.planned_end), None)
        if other is not None:
            problem(placement, "overlaps_placement", f"it overlaps the saved placement {other.id}.")
        if placement.id not in full_check_ids:
            continue
        if task is None or task.deleted_at is not None:
            problem(placement, "task_deleted", "its task was deleted.")
            continue
        if task.id not in in_range and not task.is_series:
            # (A legacy placement of a series definition is that date's occurrence; the definition itself is
            # never part of a range's tasks.)
            problem(placement, "task_out_of_range", "its task is no longer planned in this range.")
            continue
        if task.required_date is not None and task.required_date != day:
            problem(placement, "required_date_changed", f"its task must now happen on {task.required_date}.")
        if round(_minutes(placement.planned_start, placement.planned_end)) != task.estimated_duration_minutes:
            problem(placement, "duration_changed", f"its task now takes {task.estimated_duration_minutes} minutes.")
        if task.deadline is not None and placement.planned_end > task.deadline:
            problem(placement, "deadline_missed", f"it would end after the task's deadline ({task.deadline.isoformat()}).")
        if (
            preferences.optimizer_mode == OptimizerMode.ADHD_FRIENDLY
            and task.estimated_duration_minutes > 30
            and _local_minute(placement.planned_start, preferences.timezone) % 15 != 0
        ):
            problem(placement, "engine_mode_changed",
                    "the adhd_friendly engine starts tasks over 30 minutes on quarter hours only.")
        for dependency in task.dependency_ids:
            if dependency in upcoming and dependency not in kept_by_task:
                continue  # scheduled (or kept elsewhere) by this run: the engine orders it before what depends on it
            if not _dependency_done_by(dependency, placement, day, kept_by_task, dependency_placements, inputs.external):
                problem(placement, "dependency_not_satisfied", f"its dependency {dependency} no longer finishes before it.")
                break
    return problems


def _local_minute(instant: datetime, tz_name: str) -> int:
    local = instant.astimezone(ZoneInfo(tz_name))
    return local.hour * 60 + local.minute


def _dependency_done_by(
    dependency: uuid.UUID,
    placement: ScheduledTask,
    day: date_,
    kept_by_task: Mapping[uuid.UUID, ScheduledTask],
    dependency_placements: Mapping[uuid.UUID, list[ScheduledTask]],
    external: Mapping[uuid.UUID, ExternalDependency],
) -> bool:
    same_day = kept_by_task.get(dependency)
    if same_day is not None:
        return same_day.planned_end <= placement.planned_start
    if any(other.planned_date < day for other in dependency_placements.get(dependency, [])):
        return True
    resolved = external.get(dependency)
    if resolved is not None and resolved.satisfied:
        return resolved.satisfied_date < day or resolved.satisfied_at <= placement.planned_start
    return False


# -----------------------------------------------------------------------------
# Explicit rescheduling (docs/execution-rescheduling.md)
# -----------------------------------------------------------------------------


def reschedule_placement(
    service: PlanningService,
    placement_id: uuid.UUID,
    *,
    expected_version: int,
    planned_date: date_,
    timezone_name: str,
    planned_start: datetime,
    planned_end: datetime,
    replacement_id: uuid.UUID | None = None,
    task_category: str | None = None,
    at: datetime | None = None,
    template: object = PROJECT_TEMPLATE,
    snapshot: Mapping[str, object] | None = None,
) -> PlacementReschedule:
    """
    Move one saved placement to a new interval -- explicitly, atomically and
    without rewriting history -- in one transaction:

    1. the source must be a live placement at `expected_version`, of a live
       task, whose execution (if any) has not started
       (PlanningService.reschedule_source: EntityNotFoundError,
       VersionConflictError, InvalidReferenceError, HistoryProtectedError);
    2. the destination must satisfy the hard scheduling rules of the day
       engine and of incremental generation (reschedule_problems), judged
       against what is stored inside this transaction -- else
       RescheduleRejectedError listing every problem;
    3. PlanningService.apply_reschedule tombstones the source (reason
       RESCHEDULED, superseded_by_id = the replacement), inserts the
       replacement (replacement_id, or a new id) and cancels the source's
       never-started execution at `at`.

    Moving an occurrence of a recurring series to another date keeps its
    original slot identity (app/planning/occurrence.py): its own date moves
    with it -- the occurrence's required_date becomes the new date and it is
    MODIFIED, in the same transaction (PlacementReschedule.updated_task) -- so
    the date it left can never produce its work again.

    A rejected move changes nothing. The saved schedule of the affected
    dates becomes stale (its placements changed); nothing is regenerated.
    """
    with service.transaction():
        previous, task = service.reschedule_source(placement_id, expected_version=expected_version)
        try:
            candidate = ScheduledTask(
                id=replacement_id or uuid.uuid4(), task_id=task.id, user_id=previous.user_id,
                planned_date=planned_date, timezone=timezone_name, planned_start=planned_start,
                planned_end=planned_end, task_category=task_category,
                # A synchronized move carries the planning snapshot the device recorded for the replacement.
                **{name: value for name, value in (snapshot or {}).items()
                   if name in PLACEMENT_SNAPSHOT_FIELDS and name != "task_category" and value is not None},
            )
        except ValueError as error:
            raise InvalidEntityError(f"the destination is not a valid placement: {error}") from None
        moved_task = None
        if task.is_occurrence and planned_date != task.required_date:
            # Rolled back with everything else if the move is refused below.
            moved_task = service.update_task(task.model_copy(update={
                "required_date": planned_date, "occurrence_state": task.occurrence_state or OccurrenceState.MODIFIED,
            }), expected_version=task.version)
            task = moved_task
        problems = reschedule_problems(service, previous, candidate, task, template=template)
        if problems:
            raise RescheduleRejectedError(problems)
        result = service.apply_reschedule(placement_id, expected_version=expected_version, replacement=candidate, at=at)
        return replace(result, updated_task=moved_task)


def reschedule_problems(
    service: PlanningService,
    previous: ScheduledTask,
    candidate: ScheduledTask,
    task: Task,
    *,
    template: object = PROJECT_TEMPLATE,
) -> list[PlacementProblem]:
    """
    Why `candidate` (the destination of moving `previous`) breaks a hard rule;
    empty when the move is valid. The destination must: start on its
    planned_date in its timezone, on whole minutes; differ from where the
    placement already is; keep a legacy placement of a series definition on
    its own date (its date is its slot -- an occurrence of the series moves
    instead, keeping its slot identity); be the only live placement of its
    occurrence; honour the task's required date and deadline; and, like a
    placement kept by incremental generation (_kept_problems), lie inside the
    date's day window, clear of fixed blocks and of the date's other
    placements, last exactly the task's estimate, fit the engine mode and
    start after its dependencies finish. Tasks that depend on it must still
    start after it ends.
    """
    day = candidate.planned_date
    problems: list[PlacementProblem] = []

    def problem(reason: str, explanation: str) -> None:
        problems.append(PlacementProblem(candidate.id, task.id, day, reason, explanation))

    local_start = candidate.planned_start.astimezone(ZoneInfo(candidate.timezone))
    if local_start.date() != day:
        problem("wrong_date", f"it would start on {local_start.date()} in {candidate.timezone}, not on {day}.")
    if any(instant.second or instant.microsecond for instant in (candidate.planned_start, candidate.planned_end)):
        problem("not_whole_minutes", "it must start and end on whole minutes.")
    if (candidate.planned_date, candidate.timezone, candidate.planned_start, candidate.planned_end) == (
            previous.planned_date, previous.timezone, previous.planned_start, previous.planned_end):
        problem("unchanged", "it is already planned there.")
    if task.recurrence is not None and day != previous.planned_date:
        problem("recurring_occurrence_date",
                "this placement was saved for a recurring series before its occurrences existed: its date is its "
                "occurrence, so it can only move within that date. Move the series' occurrence instead.")
    if task.required_date is not None and task.required_date != day:
        problem("required_date", f"its task must happen on {task.required_date}.")
    if task.deadline is not None and candidate.planned_end > task.deadline:
        problem("deadline_missed", f"it would end after the task's deadline ({task.deadline.isoformat()}).")
    if problems:
        return problems

    inputs = read_inputs(service, day, day, scope=RangeScope.ELIGIBLE, timezone_name=candidate.timezone,
                         template=template)
    others = [placement for placement in service.placements_for_date(day) if placement.id != previous.id]
    kept_tasks = service.get_tasks_including_deleted({task.id, *(placement.task_id for placement in others)})
    problems.extend(
        found for found in _kept_problems(service, [candidate, *others], kept_tasks, inputs, day,
                                          full_check_ids={candidate.id}, kinds={candidate.id: "destination"})
        if found.placement_id == candidate.id
    )
    if task.recurrence is not None and any(placement.task_id == task.id for placement in others):
        problem("occurrence_taken", f"its recurring task already has a placement on {day}.")
    if task.is_occurrence:
        same = [placement for placement in service.active_placements_for_tasks([task.id, task.series_id]).get(task.id, [])
                if placement.id != previous.id]
        same += [placement for placement in service.active_placements_for_tasks([task.series_id]).get(task.series_id, [])
                 if placement.planned_date == task.occurrence_slot and placement.id != previous.id]
        if same:
            problem("occurrence_taken", f"this occurrence already has another placement (on {same[0].planned_date}).")

    dependents = [other.id for other in service.list_tasks() if task.id in other.dependency_ids]
    grouped = service.active_placements_for_tasks(dependents)
    for dependent_id in sorted(grouped, key=str):
        if any(placement.planned_date < day
               or (placement.planned_date == day and placement.planned_start < candidate.planned_end)
               for placement in grouped[dependent_id]):
            problem("dependent_starts_first",
                    f"the task {dependent_id} depends on it and is planned to start before it would end.")
    return problems
