"""
packaging/windows/version_info.py

The Windows version resource of ScheduleMaxing.exe (what Explorer shows under
Properties > Details), generated from app/version.py so the version is
written in exactly one place. ScheduleMaxing.spec calls write_version_file();
running this file prints the version (used by build_windows.ps1).

    python packaging/windows/version_info.py                      -> prints the version
    python packaging/windows/version_info.py --check-tag vX.Y.Z   -> fails unless the tag is this version
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
VERSION_SOURCE = ROOT / "app" / "version.py"
EXECUTABLE_NAME = "ScheduleMaxing.exe"


def read_metadata(source: Path = VERSION_SOURCE) -> dict[str, str]:
    """The string constants of app/version.py, read as text (nothing is imported)."""
    text = source.read_text(encoding="utf-8")
    values = dict(re.findall(r'^(\w+)\s*=\s*"([^"]*)"\s*$', text, flags=re.MULTILINE))
    version = values.get("__version__", "")
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError(f"{source} must define __version__ = \"MAJOR.MINOR.PATCH\" (found {version!r})")
    for name in ("APP_NAME", "APP_PUBLISHER", "APP_DESCRIPTION"):
        if not values.get(name):
            raise ValueError(f"{source} must define {name}")
    return values


def version_tuple(version: str) -> tuple[int, int, int, int]:
    major, minor, patch = (int(part) for part in version.split("."))
    return (major, minor, patch, 0)


def render(metadata: dict[str, str]) -> str:
    version = metadata["__version__"]
    numbers = version_tuple(version)
    strings = {
        "CompanyName": metadata["APP_PUBLISHER"],
        "FileDescription": metadata["APP_NAME"],
        "FileVersion": version,
        "InternalName": Path(EXECUTABLE_NAME).stem,
        "OriginalFilename": EXECUTABLE_NAME,
        "ProductName": metadata["APP_NAME"],
        "ProductVersion": version,
        "Comments": metadata["APP_DESCRIPTION"],
    }
    entries = ",\n        ".join(f"StringStruct({key!r}, {value!r})" for key, value in strings.items())
    return f"""# Generated by packaging/windows/version_info.py from app/version.py. Do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={numbers}, prodvers={numbers}, mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1,
                    subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        {entries}
    ])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def write_version_file(target: str | Path) -> Path:
    target = Path(target)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(read_metadata()), encoding="utf-8")
    return target


def check_tag(tag: str, version: str | None = None) -> str | None:
    """None when the release tag is exactly "v" + the application version; otherwise what is wrong."""
    version = version or read_metadata()["__version__"]
    if tag != f"v{version}":
        return f"tag {tag!r} does not match the version in app/version.py ({version!r}): expected 'v{version}'"
    return None


if __name__ == "__main__":
    if len(sys.argv) > 2 and sys.argv[1] == "--check-tag":
        problem = check_tag(sys.argv[2])
        if problem:
            sys.exit(problem)
        print(f"{sys.argv[2]} matches app/version.py")
    elif len(sys.argv) > 1:
        print(write_version_file(sys.argv[1]))
    else:
        print(read_metadata()["__version__"])
