"""
app/persistence/verify_render.py

An explicit, opt-in verification of the direct PostgreSQL storage against a
real database (docs/render-direct-desktop.md). It never runs by itself:
importing this module does nothing, no test hook calls it, and every mode
must be chosen on the command line.

    python -m app.persistence.verify_render --env-file .env --check-only
    python -m app.persistence.verify_render --env-file .env --write-sample \\
        --email Ramtin1383.5@gmail.com --display-name Ramtin \\
        --anchor-date 2026-09-28 --timezone America/Vancouver [--dependency-date 2026-09-29]

--check-only    connection, TLS mode and schema revision. No DDL, no account,
                no writes. Exit 0 = current, 1 = schema not current, 2 = failure.

--write-sample  requires the schema at the current revision (migrate first,
                explicitly: `python -m backend.migrate --env-file .env upgrade`).
                1. The account: created if absent (the password is asked twice),
                   otherwise signed in with the supplied password -- a wrong
                   password stops everything; a password is never reset.
                2. samples/inputs/valid_single_day_basic.csv (3 flexible tasks, 4
                   fixed blocks, day 1, no dependencies -- asserted) converted by
                   the ordinary legacy importer onto --anchor-date in --timezone,
                   then given stable seed identities (uuid5 of fixture version,
                   user, date, timezone and CSV line), dependencies remapped.
                   Seeding is one transaction under the user's lock: missing
                   records are created; identical ones are left alone; edited or
                   deleted ones are reported as a conflict and nothing is
                   overwritten. A date that already holds other records of the
                   user is refused (nothing is replaced or reset).
                3. A neutral preference layer for that date (the precise engine,
                   study multiplier 1.0): created if absent, left if identical, a
                   conflict if the user's layer differs.
                4. The date's schedule, generated by the shared planning workflow
                   (an unchanged date is "already current": nothing is written).
                5. One scheduled execution for the sample's Study Session
                   placement (get-or-create; no work is invented).
                6. The session is closed and the engine disposed; a new one
                   signs in again and reads everything back through the public
                   services, checking ids, ownership, values, placement validity
                   and freshness.
                7. Password checks within a stated scope (see _password_scope).
                A repeated run finds everything in place and writes nothing.
                If a run fails after earlier steps committed, the summary says
                which steps finished; running it again resumes safely.

Output is a safe summary only: never a URL, host, password, hash or SQL.
The password is read with getpass (no default, never an argument) and held
only while the command runs; no transaction is open while it is typed or
while the optimizer runs.
"""

from __future__ import annotations

import argparse
import csv
import getpass
import io
import logging
import sys
import uuid
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAIN_SAMPLE = ROOT / "samples" / "inputs" / "valid_single_day_basic.csv"
DEPENDENCY_SAMPLE = ROOT / "samples" / "inputs" / "dependency_chain_linear.csv"
FIXTURE_VERSION = "render-sample-v1"
SEED_NAMESPACE = uuid.UUID("7a0f1c5e-2b8d-4c3a-9e61-5f2d8b4a7c10")
#: What the main sample must contain (checked against the file itself before anything is written).
MAIN_EXPECTED = {"tasks": 3, "fixed_blocks": 4, "day_indexes": {1}, "dependencies": 0}
TASK_CONTENT = ("project_id", "name", "category", "tags", "estimated_duration_minutes", "priority", "required",
                "required_date", "preferred_dates", "preferred_time_window", "dependency_ids", "deadline", "recurrence")
BLOCK_CONTENT = ("label", "category", "planned_date", "timezone", "planned_start", "planned_end")
STEPS = ("connection", "schema", "account", "seed", "preference", "generation", "execution", "read-back",
         "password-scope")


class VerificationError(Exception):
    """A step failed; the message is safe to print."""


class SeedConflict(VerificationError):
    """Seed records or the date's data differ from what this command would write; nothing was overwritten."""


# -----------------------------------------------------------------------------
# The sample and its stable identities
# -----------------------------------------------------------------------------


@dataclass(frozen=True)
class Seed:
    fixture: str
    day: date
    timezone: str
    tasks: list  # app.planning.models.Task, owner and stable ids set
    fixed_blocks: list  # app.planning.models.FixedBlock
    day_indexes: set[int]
    dependency_count: int


def seed_id(user_id: uuid.UUID, fixture: str, day: date, timezone_name: str, line: int) -> uuid.UUID:
    return uuid.uuid5(SEED_NAMESPACE, f"{FIXTURE_VERSION}/{fixture}/{user_id}/{day.isoformat()}/{timezone_name}/{line}")


def load_seed(path: Path, *, user_id: uuid.UUID, day: date, timezone_name: str) -> Seed:
    """The CSV through the ordinary legacy importer, re-keyed with stable ids (dependencies remapped)."""
    from app.planning.csv_import import parse_legacy_csv, read_csv_text

    text = read_csv_text(path)
    parsed = parse_legacy_csv(text, anchor_date=day, timezone=timezone_name, source=path.name)
    rows = list(csv.DictReader(io.StringIO(text)))
    block_lines = [index + 2 for index, row in enumerate(rows) if (row.get("fixed") or "").strip().lower() == "true"]
    day_indexes = {int(row["date"]) for row in rows}
    task_ids = {task.id: seed_id(user_id, path.name, day, timezone_name, parsed.lines_by_task_id[task.id])
                for task in parsed.tasks}
    tasks = [task.model_copy(update={"id": task_ids[task.id], "user_id": user_id,
                                     "dependency_ids": [task_ids[d] for d in task.dependency_ids]})
             for task in parsed.tasks]
    blocks = [block.model_copy(update={"id": seed_id(user_id, path.name, day, timezone_name, line), "user_id": user_id})
              for block, line in zip(parsed.fixed_blocks, block_lines)]
    return Seed(path.name, day, timezone_name, tasks, blocks, day_indexes,
                sum(len(task.dependency_ids) for task in tasks))


def _content(model, fields: tuple[str, ...]) -> dict:
    return model.model_dump(include=set(fields))


# -----------------------------------------------------------------------------
# Report
# -----------------------------------------------------------------------------


@dataclass
class Report:
    mode: str
    steps: dict[str, str] = field(default_factory=lambda: {step: "not run" for step in STEPS})
    facts: dict[str, str] = field(default_factory=dict)
    problem: str | None = None

    def done(self, step: str, detail: str = "ok") -> None:
        self.steps[step] = detail

    def failed(self, step: str, message: str) -> None:
        self.steps[step] = "FAILED"
        self.problem = message

    @property
    def ok(self) -> bool:
        return self.problem is None

    def lines(self) -> list[str]:
        outcome = "SUCCESS" if self.ok else "FAILURE"
        lines = [f"Schedule Maxing direct-database verification ({self.mode}): {outcome}"]
        lines += [f"  {name}: {value}" for name, value in self.facts.items()]
        if self.problem:
            lines.append(f"  problem: {self.problem}")
        relevant = STEPS[:2] if self.mode == "check-only" else STEPS
        lines.append("  steps: " + ", ".join(f"{step} {self.steps[step]}" for step in relevant))
        return lines


def _safe(error: BaseException) -> str:
    from app.execution.errors import ExecutionError
    from app.persistence.errors import DirectPersistenceError
    from app.planning.errors import PlanningError

    if isinstance(error, (VerificationError, DirectPersistenceError, PlanningError, ExecutionError)):
        return str(error)
    try:
        from sqlalchemy.exc import SQLAlchemyError

        if isinstance(error, SQLAlchemyError):
            from app.persistence.direct import safe_database_error

            return str(safe_database_error(error))
    except ModuleNotFoundError:
        pass
    return f"an unexpected {type(error).__name__} occurred"


class _Capture(logging.Handler):
    """Collects every log message emitted while the command runs (for the password scope check)."""

    def __init__(self) -> None:
        super().__init__(logging.DEBUG)
        self.messages: list[str] = []

    def emit(self, record: logging.LogRecord) -> None:
        try:
            self.messages.append(record.getMessage())
        except Exception:  # noqa: BLE001 - a malformed record must not break the run
            pass


# -----------------------------------------------------------------------------
# Steps
# -----------------------------------------------------------------------------


def _connect(settings, backend_factory, report: Report):
    facts = settings.describe()
    where = ("local server (TLS not required)" if facts["local_server"] == "True"
             else f"remote server over TLS (sslmode={facts['tls']})")
    report.facts["database"] = f"DATABASE_URL from the {settings.source}; {where}"
    backend = backend_factory(settings)
    current, head = backend.schema_revision()
    report.done("connection")
    report.facts["schema"] = f"revision {current or 'none'} (this version needs {head})"
    return backend, current, head


def _account(backend, args, password_source, report: Report):
    from app.persistence.errors import InvalidCredentialsError

    exists = backend.account_exists(email=args.email)
    password = password_source(f"Password for {args.email.strip()}: ")
    if not password:
        raise VerificationError("No password was entered.")
    if not exists:
        if password_source("Repeat the password for the new account: ") != password:
            raise VerificationError("The two passwords differ; nothing was created.")
        backend.register(email=args.email, password=password, display_name=args.display_name)
    try:
        account = backend.sign_in(email=args.email, password=password)
    except InvalidCredentialsError:
        raise VerificationError("The password does not match the existing account; nothing was changed "
                                "(an existing password is never reset).") from None
    identity = account.identity
    report.facts["account"] = (f"{identity.display_name or '(no display name)'} <{identity.email}> "
                               f"({'created' if not exists else 'existing'}, password verified)")
    if identity.display_name != args.display_name.strip():
        report.facts["account"] += "; its stored display name differs and was left unchanged"
    report.done("account", "created" if not exists else "existing")
    return account, password


def _check_date_is_free(planning, seed: Seed) -> None:
    """Refuse a date holding other records of the user: generation there would reschedule them."""
    seed_ids = {task.id for task in seed.tasks} | {block.id for block in seed.fixed_blocks}
    others = [task for task in planning.tasks_planned_in_range(seed.day, seed.day, timezone_name=seed.timezone)
              if task.id not in seed_ids]
    others += [block for block in planning.fixed_blocks_for_date(seed.day) if block.id not in seed_ids]
    if others:
        raise SeedConflict(
            f"{seed.day.isoformat()} already holds {len(others)} other task(s)/fixed block(s) of this account (undated "
            "tasks count, since generation would schedule them). Nothing was written; choose another --anchor-date.")


def _apply_seed(planning, seed: Seed) -> int:
    """Create missing seed records in one transaction; identical ones stay; changed ones are a conflict. Returns created."""
    with planning.transaction():  # the user's lock: concurrent runs serialize here
        _check_date_is_free(planning, seed)
        stored_tasks = planning.get_tasks_including_deleted([task.id for task in seed.tasks])
        conflicts, missing_tasks, missing_blocks = [], [], []
        for task in seed.tasks:
            stored = stored_tasks.get(task.id)
            if stored is None:
                missing_tasks.append(task)
            elif stored.deleted_at is not None or _content(stored, TASK_CONTENT) != _content(task, TASK_CONTENT):
                conflicts.append(f"task {task.name!r} was {'deleted' if stored.deleted_at else 'edited'}")
        for block in seed.fixed_blocks:
            stored = planning.get_fixed_block(block.id, include_deleted=True)
            if stored is None:
                missing_blocks.append(block)
            elif stored.deleted_at is not None or _content(stored, BLOCK_CONTENT) != _content(block, BLOCK_CONTENT):
                conflicts.append(f"fixed block {block.label!r} was {'deleted' if stored.deleted_at else 'edited'}")
        if conflicts:
            raise SeedConflict("The seeded records changed since they were created (" + "; ".join(conflicts) +
                               "). They were left as they are; nothing was overwritten.")
        if missing_tasks:
            planning.create_tasks(missing_tasks)
        for block in missing_blocks:
            planning.create_fixed_block(block)
        return len(missing_tasks) + len(missing_blocks)


def seed_preferences():
    from app.planning.preferences import OptimizerMode, PreferenceOverrides

    return PreferenceOverrides(optimizer_mode=OptimizerMode.PRECISE_GREEDY, category_multipliers={"study": 1.0})


def _apply_preference(planning, day: date) -> str:
    wanted = seed_preferences()
    with planning.transaction():
        stored = planning.date_preferences(day)
        if stored is None:
            planning.save_date_preferences(day, wanted)
            return "created"
        if stored.overrides != wanted:
            raise SeedConflict(f"{day.isoformat()} already has a preference layer that differs from the sample's; it "
                               "was left unchanged.")
        return "already present"


def _generate(planning, seed: Seed) -> str:
    from app.planning import workflow
    from app.planning.application import RangeScope

    outcome = workflow.generate(planning, range_start=seed.day, range_end=seed.day, timezone_name=seed.timezone,
                                scope=RangeScope.PLANNED)
    return outcome.status


def _study_execution(account, planning, seed: Seed):
    study = next(task for task in seed.tasks if task.name == "Study Session")
    placement = next((p for p in planning.placements_for_date(seed.day) if p.task_id == study.id), None)
    if placement is None:
        raise VerificationError("The Study Session was not placed, so no execution could be recorded for it.")
    return account.execution_service().get_or_create_canonical_execution(planning.get_task(study.id), placement)


def _change_count(backend, user_id: uuid.UUID) -> int:
    from sqlalchemy import func, select

    from backend import models

    with backend.operation() as session:
        return session.scalar(select(func.count()).select_from(models.ChangeLogEntry)
                              .where(models.ChangeLogEntry.user_id == user_id))


def _read_back(account, seed: Seed, execution_id: str) -> dict[str, int]:
    """Everything the run stored, re-read through the public services of a fresh connection, and checked."""
    from app.planning import workflow

    planning = account.planning_service()
    owner = account.user_id
    tasks = planning.get_tasks([task.id for task in seed.tasks]).tasks
    if set(tasks) != {task.id for task in seed.tasks}:
        raise VerificationError("Not every seeded task could be read back.")
    for task in seed.tasks:
        stored = tasks[task.id]
        if stored.user_id != owner or _content(stored, TASK_CONTENT) != _content(task, TASK_CONTENT):
            raise VerificationError(f"The task {task.name!r} read back with different values or owner.")
    blocks = {block.id: block for block in planning.fixed_blocks_for_date(seed.day)}
    for block in seed.fixed_blocks:
        stored = blocks.get(block.id)
        if stored is None or stored.user_id != owner or _content(stored, BLOCK_CONTENT) != _content(block, BLOCK_CONTENT):
            raise VerificationError(f"The fixed block {block.label!r} read back missing or different.")
    placements = planning.placements_for_date(seed.day)
    by_task = {task.id: task for task in seed.tasks}
    intervals = [(block.planned_start, block.planned_end) for block in seed.fixed_blocks]
    for placement in placements:
        task = by_task.get(placement.task_id)
        if task is None or placement.user_id != owner or placement.planned_date != seed.day:
            raise VerificationError("A placement on the seed date does not belong to the seeded tasks.")
        minutes = (placement.planned_end - placement.planned_start).total_seconds() / 60
        if minutes != task.estimated_duration_minutes:
            raise VerificationError(f"The placement of {task.name!r} does not last its estimated duration.")
        for start, end in intervals:
            if placement.planned_start < end and start < placement.planned_end:
                raise VerificationError(f"The placement of {task.name!r} overlaps a fixed block or another task.")
        intervals.append((placement.planned_start, placement.planned_end))
    for task in seed.tasks:  # dependencies are respected (the dependency fixture's chain)
        own = next((p for p in placements if p.task_id == task.id), None)
        for dependency in task.dependency_ids:
            before = next((p for p in placements if p.task_id == dependency), None)
            if own is not None and (before is None or before.planned_end > own.planned_start):
                raise VerificationError(f"{task.name!r} is placed before a task it depends on.")
    freshness = workflow.day_freshness(planning, [seed.day], seed.timezone)[seed.day]
    if freshness.status != workflow.Freshness.CURRENT:
        raise VerificationError(f"The seed date's schedule is not current after reopening ({freshness.status.value}).")
    layer = planning.date_preferences(seed.day)
    if layer is None or layer.overrides != seed_preferences():
        raise VerificationError("The sample's preference layer did not read back identically.")
    counts = {"tasks": len(tasks), "fixed_blocks": len(seed.fixed_blocks), "placements": len(placements)}
    if execution_id:
        executions = account.execution_service()
        execution = executions.get_execution(execution_id)
        if execution.user_id != owner or execution.status.value != "scheduled" or executions.list_sessions(execution_id):
            raise VerificationError("The sample execution read back with another owner, status or invented sessions.")
        counts["executions"] = 1
    return counts


def _password_scope(backend, account, password: str, capture: _Capture, seeds: list[Seed]) -> str:
    """
    Scope, stated in the output: the account's stored credential is a valid
    Argon2id hash that verifies the password; the schema has no plaintext
    credential column; the records and change-log snapshots written for the
    seeded ids, and every log message of this run, do not contain the
    password. The comparison happens here in Python -- the password is never
    sent in a search statement -- and this is not a database-wide audit.
    """
    from sqlalchemy import inspect as sa_inspect
    from sqlalchemy import select

    from backend import models, snapshots
    from backend.passwords import verify_password

    with backend.operation() as session:
        stored_hash = session.scalar(select(models.User.password_hash).where(models.User.id == account.user_id))
        columns = {(table, column["name"]) for table in sa_inspect(session.connection()).get_table_names()
                   for column in sa_inspect(session.connection()).get_columns(table)}
        entity_ids = [record.id for seed in seeds for record in (*seed.tasks, *seed.fixed_blocks)]
        entries = list(session.scalars(select(models.ChangeLogEntry).where(
            models.ChangeLogEntry.user_id == account.user_id, models.ChangeLogEntry.entity_id.in_(entity_ids))))
        written = [snapshots.decode(entry.revision) for entry in entries]
    if not stored_hash or not stored_hash.startswith("$argon2id$") or not verify_password(password, stored_hash):
        raise VerificationError("The stored credential is not a valid Argon2id hash of the password.")
    credential_columns = {pair for pair in columns if any(word in pair[1] for word in ("password", "secret", "token"))}
    if credential_columns - {("users", "password_hash"), ("browser_sessions", "token_hash"),
                             ("password_recovery_tokens", "token_hash"), ("refresh_credentials", "token_hash")}:
        raise VerificationError("The schema has a credential column that is not a hash.")
    texts = [repr(record) for record in written] + [repr(record.model_dump()) for seed in seeds
                                                     for record in (*seed.tasks, *seed.fixed_blocks)]
    if any(password in text for text in texts) or any(password in message for message in capture.messages):
        raise VerificationError("The password appeared in data or log output written by this run.")
    return (f"stored credential is an Argon2id hash that verifies; no plaintext credential column; password absent "
            f"from {len(written)} change-log snapshot(s) of the seeded records and {len(capture.messages)} log "
            "message(s) of this run (scope: this account and this run, not a database-wide audit)")


# -----------------------------------------------------------------------------
# Modes
# -----------------------------------------------------------------------------


def check_only(settings, backend_factory) -> tuple[Report, int]:
    report = Report("check-only")
    backend = None
    try:
        backend, current, head = _connect(settings, backend_factory, report)
        if current != head:
            report.failed("schema", f"the schema is not current; after a backup run 'python -m backend.migrate "
                                    f"--env-file .env upgrade' (current {current or 'none'}, needed {head})")
            return report, 1
        report.done("schema", "current")
        return report, 0
    except Exception as error:  # noqa: BLE001 - reported safely
        report.failed(next(step for step in STEPS if report.steps[step] == "not run"), _safe(error))
        return report, 2
    finally:
        if backend is not None:
            backend.close()


def write_sample(args, settings, backend_factory, password_source) -> tuple[Report, int]:
    report = Report("write-sample")
    capture = _Capture()
    logging.getLogger().addHandler(capture)
    backend = account = password = None
    step = "connection"
    try:
        backend, current, head = _connect(settings, backend_factory, report)
        step = "schema"
        if current != head:
            raise VerificationError(f"the schema is not current (current {current or 'none'}, needed {head}); nothing "
                                    "was written. After a backup, run 'python -m backend.migrate --env-file .env upgrade'.")
        report.done("schema", "current")

        step = "account"
        account, password = _account(backend, args, password_source, report)
        planning = account.planning_service()

        step = "seed"
        seeds = [load_seed(MAIN_SAMPLE, user_id=account.user_id, day=args.anchor_date, timezone_name=args.timezone)]
        main = seeds[0]
        found = {"tasks": len(main.tasks), "fixed_blocks": len(main.fixed_blocks), "day_indexes": main.day_indexes,
                 "dependencies": main.dependency_count}
        if found != MAIN_EXPECTED:
            raise VerificationError("The main sample file no longer has the expected content (3 flexible tasks, "
                                    "4 fixed blocks, day 1, no dependencies); nothing was written.")
        if args.dependency_date is not None:
            seeds.append(load_seed(DEPENDENCY_SAMPLE, user_id=account.user_id, day=args.dependency_date,
                                   timezone_name=args.timezone))
        before = _change_count(backend, account.user_id)
        created = sum(_apply_seed(planning, seed) for seed in seeds)
        report.done("seed", f"{created} record(s) created" if created else "already seeded")
        report.facts["seed"] = f"{main.fixture} ({FIXTURE_VERSION}) on {main.day.isoformat()} in {main.timezone}"
        report.facts["dependencies"] = ("none in the main sample (not applicable)" + (
            f"; {seeds[1].fixture} on {seeds[1].day.isoformat()}: {seeds[1].dependency_count} dependencies"
            if len(seeds) > 1 else ""))

        step = "preference"
        report.done("preference", "; ".join(_apply_preference(planning, seed.day) for seed in seeds))

        step = "generation"
        report.done("generation", "; ".join(_generate(planning, seed) for seed in seeds))

        step = "execution"
        execution = _study_execution(account, planning, main)
        report.done("execution", f"{execution.status.value} (sample-derived, no work recorded)")
        written = _change_count(backend, account.user_id) - before
        report.facts["idempotence"] = ("nothing needed changing (0 new change-log entries)" if not written else
                                       f"{written} change(s) written; a repeated run writes none")

        step = "read-back"
        backend.close()  # a fresh Engine and session: nothing read back comes from this run's objects
        backend = backend_factory(settings)
        account = backend.sign_in(email=args.email, password=password)
        counts = [_read_back(account, seed, execution.id if seed is main else "") for seed in seeds]
        main_counts = counts[0]
        report.facts["records"] = (f"{main_counts['tasks']} tasks, {main_counts['fixed_blocks']} fixed blocks, "
                                   f"{main_counts['placements']} placements, {main_counts['executions']} execution "
                                   "(scheduled)")
        report.facts["reopened connection"] = "signed in again; ids, owner, values, placements and freshness verified"
        report.facts["preference and freshness"] = "date layer read back identically; the date is current"
        report.done("read-back")

        step = "password-scope"
        report.facts["password check"] = _password_scope(backend, account, password, capture, seeds)
        report.done("password-scope")
        return report, 0
    except Exception as error:  # noqa: BLE001 - reported safely; completed steps stay listed
        report.failed(step, _safe(error))
        return report, 1 if isinstance(error, SeedConflict) else 2
    finally:
        password = None  # drop the reference (Python cannot promise to erase the string from memory)
        logging.getLogger().removeHandler(capture)
        if account is not None:
            account.sign_out()
        if backend is not None:
            backend.close()


# -----------------------------------------------------------------------------
# Command line
# -----------------------------------------------------------------------------


def _date(value: str) -> date:
    try:
        return date.fromisoformat(value)
    except ValueError:
        raise argparse.ArgumentTypeError("use YYYY-MM-DD") from None


def _zone(value: str) -> str:
    from app.planning.time import validate_timezone

    try:
        validate_timezone(value)
    except ValueError:
        raise argparse.ArgumentTypeError("use an IANA time zone such as America/Vancouver") from None
    return value


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="python -m app.persistence.verify_render",
                                description="Opt-in verification of direct PostgreSQL storage (see "
                                            "docs/render-direct-desktop.md). Prints a safe summary only.")
    p.add_argument("--env-file", metavar="PATH", help="read DATABASE_URL from this file (the environment still wins)")
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check-only", action="store_true", help="connection, TLS and schema revision; writes nothing")
    mode.add_argument("--write-sample", action="store_true", help="the account and the idempotent sample (see above)")
    p.add_argument("--email", help="the account's email (required with --write-sample)")
    p.add_argument("--display-name", help="the display name of a new account (required with --write-sample)")
    p.add_argument("--anchor-date", type=_date, help="the date day 1 of the sample becomes (required with --write-sample)")
    p.add_argument("--timezone", type=_zone, help="the IANA time zone of the sample (required with --write-sample)")
    p.add_argument("--dependency-date", type=_date,
                   help="optional: also seed samples/inputs/dependency_chain_linear.csv on this (different) date")
    return p


def main(argv: list[str] | None = None, *, backend_factory: Callable | None = None,
         password_source: Callable[[str], str] = getpass.getpass, environ=None, out=print) -> int:
    args = parser().parse_args(argv)
    if args.write_sample:
        missing = [name for name in ("email", "display_name", "anchor_date", "timezone") if getattr(args, name) is None]
        if missing:
            parser().error("--write-sample needs " + ", ".join("--" + name.replace("_", "-") for name in missing))
        if args.dependency_date is not None and args.dependency_date == args.anchor_date:
            parser().error("--dependency-date must differ from --anchor-date")

    from app.persistence import load_direct_settings, open_direct_backend
    from app.persistence.errors import DirectPersistenceError

    try:
        settings = load_direct_settings(env_file=args.env_file, environ=environ)
    except DirectPersistenceError as error:
        out(f"Schedule Maxing direct-database verification: FAILURE\n  problem: {error}\n  (nothing was run)")
        return 2
    factory = backend_factory or (lambda direct_settings: open_direct_backend(direct_settings, check_schema=False))
    if args.check_only:
        report, code = check_only(settings, factory)
    else:
        report, code = write_sample(args, settings, factory, password_source)
    report.facts.setdefault("checked at", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"))
    out("\n".join(report.lines()))
    return code


if __name__ == "__main__":
    sys.exit(main())
