# config/settings.py

# Time model
TIME_SLOT_MINUTES = 30
DEFAULT_MODE = "day"

# Reward weights
WEIGHT_IMPORTANCE = 5
WEIGHT_TIME_BONUS = 3
WEIGHT_TAG_RELATION = 2
WEIGHT_FRAGMENTATION_PENALTY = -4

# Constraints
ALLOW_OVERLAP = False
ALLOW_TASK_SPLITTING = False
MAX_TASKS_PER_DAY = 12

# Optimizer
DEFAULT_OPTIMIZER = "greedy"
MAX_BACKTRACK_STATES = 10000
